language: ruby
rvm:
- 2.1
script: ./script/cibuild# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
