highlighter: pygments
exclude: [
  README.md,
  package.json,
  gruntfile.js,
  sass/,
  vendor
]

paginate: 5

share_twitter: true
share_google: false
share_facebook: false
share_reddit: false

# Site settings
title: Gamelinchpin
author: "Simeon Pashley"
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Some random collection of notes, posts and longer form writing.
  Mostly about technology, web development, games and whatever else I find
  interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gamelinchpin.github.io" # the base hostname & protocol for your site
twitter_username: simeonpashley
github_username:  gamelinchpin

permalink: /:year/:month/:title

disqus_short_name: gamelinchpingithubio

# Build settings
markdown: kramdown

# Put the authors in alphabetical order
authors:
  gamelinchpin:
    name: Simeon Pashley
    email: ""
    position: ""
    start_date: 1986-02-01
    github: gamelinchpin
    twitter: simeonpashley
    gplus: +SimeonPashley
    linkedin: https://uk.linkedin.com/in/simeonpashley/
    gravatar: e75deb5e1dc8de89fecefba23a1efd97
    about: ""
